// <auto-generated />
using System;
using CoffeeShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShop.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    [Migration("20250506151241_SeedSubcategoriesAndProducts")]
    partial class SeedSubcategoriesAndProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://foodsafetyworks.com/wp-content/uploads/2023/01/04_22_HERO2_NA_Cocktails_GettyImages-1145767236_1920x1280-1200x750.jpg",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://img.freepik.com/premium-photo/wide-selection-snacks-beer_127657-11986.jpg",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://tasteoffrancemag.com/wp-content/uploads/2023/01/shutterstock_2122346009-scaled.jpg",
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://www.allrecipes.com/thmb/kTq3rdclrgW3U30RlND_QCMifnQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/What-Is-a-Mocktail-4x3-05a75e02326d4cdb8c1f310c7ea8c983.jpg",
                            Name = "Mocktails",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://th.bing.com/th/id/OIP.obyUm91cu_jAtnrJPxSAGwHaEi?rs=1&pid=ImgDetMain",
                            Name = "Soft Drinks",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://th.bing.com/th/id/OIP.bkIw6G3GakAWI8VEjp1AKwHaFN?w=1280&h=901&rs=1&pid=ImgDetMain",
                            Name = "Tea",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://th.bing.com/th/id/R.3c67e53d682589dcb8ce02dd3ac1e20c?rik=LeUqj%2bnBd3%2f0WA&riu=http%3a%2f%2fwallup.net%2fwp-content%2fuploads%2f2017%2f11%2f17%2f239445-coffee-coffee_beans-cup.jpg&ehk=%2bEd%2bhMjaHGMrExklwM9MNbALfkaDNqvDmS67gs%2bf2OA%3d&risl=&pid=ImgRaw&r=0",
                            Name = "Coffee",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://th.bing.com/th/id/OIP.8HPVNhrfz1Y-hVBokGwUiQHaEK?rs=1&pid=ImgDetMain",
                            Name = "Matcha",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://imgeng.jagran.com/images/2023/sep/healthy-juices1693713856763.jpg",
                            Name = "Juices",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://img.freepik.com/premium-photo/variety-smoothies-are-display-front-wooden-table_265515-6931.jpg",
                            Name = "Smoothies",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://th.bing.com/th/id/R.7d973c7f0e96d9c0c1388e2862008bf0?rik=vLG%2fD9Hh3wS7PA&riu=http%3a%2f%2fdontchangemuch.ca%2fwp-content%2fuploads%2f2014%2f04%2favoid-salty-snacks-600x400.jpg&ehk=3NoWPEt7TopX287Casw%2b4f7ddQFyTyjZRGVzmP0ftDs%3d&risl=&pid=ImgRaw&r=0",
                            Name = "Salty Snacks",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://th.bing.com/th/id/OIP.7Au8sSgD3sKhERqekJXWVgHaE6?rs=1&pid=ImgDetMain",
                            Name = "Sweet Snacks",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://drop.ndtv.com/albums/COOKS/5-quick-snacks-_638097489443661172/638097489474374702.png",
                            Name = "Quick Snacks",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0587/2045/2783/files/Best_Vegan_Snacks.jpg?v=1657782422",
                            Name = "Vegan Snacks",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://familyapp.com/wp-content/uploads/2022/07/25-amazing-ideas-for-gluten-free-snacks.jpg",
                            Name = "Gluten Free Snacks",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Pies-and-Cobblers.jpg",
                            Name = "Pies & Cobblers",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Cookies.jpg",
                            Name = "Cookies",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Cakes.jpg",
                            Name = "Cakes",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Tarts.jpg",
                            Name = "Tarts",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Ice-Cream.jpg",
                            Name = "Ice Cream",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Custard.jpg",
                            Name = "Custards",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Brownies.jpg",
                            Name = "Brownies",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Pastries.jpg",
                            Name = "Pastries",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Donuts.jpg",
                            Name = "Donuts",
                            ParentCategoryId = 3
                        });
                });

            modelBuilder.Entity("CoffeeShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeShop.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CoffeeShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Detail = "This drink, sweetened with honey syrup, serves up all the winter vibes. Mix up a big batch in a pitcher for everyone to enjoy at your next gathering! This drink is also great for summer weather as a refreshing pick-me-up.",
                            ImageUrl = "https://img.buzzfeed.com/buzzfeed-static/static/2022-12/8/19/asset/70b89f8abc55/sub-buzz-1147-1670529545-28.jpg?downsize=700%3A%2A&output-quality=auto&output-format=auto",
                            IsTrendingProduct = false,
                            Name = "Cranberry Rosemary Herb Soda",
                            Price = 150m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Detail = "With the rich flavors of black cherry juice, cola, and blackberry syrup, this dark and mysterious drink is taken to the next level with the magical effect of dry ice. Garnished with fresh blackberries, it’s as delicious as it is dramatic.",
                            ImageUrl = "https://mybartender.com/wp-content/uploads/2024/10/Black-Cauldron-Mocktail-1536x858.png",
                            IsTrendingProduct = false,
                            Name = "Black Cauldron Mocktail",
                            Price = 120m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Detail = "With a blend of apple juice, tangy lemon juice, a hint of sweetness from granny smith apple syrup, and served over ice, this mocktail is a burst of crisp flavors.",
                            ImageUrl = "https://cf.ltkcdn.net/cocktails/images/std-xs/283957-340x227-mocktail-appletini.jpg",
                            IsTrendingProduct = false,
                            Name = "Appletini Mocktail",
                            Price = 160m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Detail = "Soft Drink",
                            ImageUrl = "https://businesschronicler.com/wp-content/uploads/2022/09/Coca-Cola-Business-History-950x650.png",
                            IsTrendingProduct = false,
                            Name = "Coca-Cola ",
                            Price = 150m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Detail = "Soft Drink",
                            ImageUrl = "https://creativereview.imgix.net/content/uploads/2023/03/pepsi-branding-1.jpg?auto=compress,format&q=60&w=1920&h=1435",
                            IsTrendingProduct = false,
                            Name = "Pepsi",
                            Price = 120m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Detail = "Soft Drink",
                            ImageUrl = "https://etimg.etb2bimg.com/photo/89492209.cms",
                            IsTrendingProduct = false,
                            Name = "Thumbs Up",
                            Price = 160m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            Detail = "Soft Drink",
                            ImageUrl = "https://brewbuch.com/wp-content/uploads/2023/05/black-tea.jpg",
                            IsTrendingProduct = false,
                            Name = "Black Tea",
                            Price = 160m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Detail = "Soft Drink",
                            ImageUrl = "https://brewbuch.com/wp-content/uploads/2023/05/green-tea.jpg",
                            IsTrendingProduct = false,
                            Name = "Green Tea",
                            Price = 160m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Detail = "Soft Drink",
                            ImageUrl = "https://brewbuch.com/wp-content/uploads/2023/05/herbal-tea.jpg",
                            IsTrendingProduct = false,
                            Name = "Herbal Tea",
                            Price = 160m
                        },
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Detail = "The Americano coffee is a classic espresso-based drink that is simple yet satisfying. It is made by adding hot water to a shot of espresso, which dilutes the intensity and results in a rich, bold coffee with a smooth finish. This versatile drink can be enjoyed on its own or with a splash of cream, making it a popular choice for coffee lovers everywhere. Whether you need a pick-me-up in the morning or a midday boost, the Americano is a dependable choice that never fails to deliver.",
                            ImageUrl = "https://res.cloudinary.com/durcypdqc/image/upload/v1675704066/Coffee%20Shop%20Asp%20.NET%20Core%20Assets/americano_gorkrx.png",
                            IsTrendingProduct = false,
                            Name = "Americano",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Detail = "Cortado\", Detail = \"Cortado coffee is a traditional Spanish coffee beverage that has gained popularity worldwide. It is a smooth and creamy coffee that combines equal parts of espresso and warm milk, creating a perfect balance of intense coffee flavor and rich creaminess. This coffee is perfect for coffee lovers who want a bit of sweetness in their coffee without sacrificing its robust flavor. Cortado coffee is made using high-quality espresso beans, freshly brewed and combined with steamed milk to create a velvety, smooth and flavorful coffee. Whether you are a coffee aficionado or a coffee lover, Cortado coffee is the perfect coffee to start your day with or to enjoy in the afternoon. Try our Cortado coffee today and experience the unique and satisfying taste of this traditional Spanish coffee beverage.",
                            ImageUrl = "https://res.cloudinary.com/durcypdqc/image/upload/v1675704067/Coffee%20Shop%20Asp%20.NET%20Core%20Assets/cortado_rs5lwa.png",
                            IsTrendingProduct = true,
                            Name = "Cortado",
                            Price = 25m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Detail = "Mocha coffee is a rich and creamy blend that combines the bold flavor of coffee with the sweetness of chocolate. This delectable drink is perfect for those who love the taste of chocolate but also enjoy a good coffee. Mocha coffee is made with a shot of espresso, steamed milk, and chocolate syrup. The result is a smooth and creamy drink with a sweet, chocolatey taste and a strong coffee finish. Whether you are looking for a sweet and indulgent treat or a pick-me-up in the morning, Mocha coffee is sure to satisfy your cravings. Get your fix of this delicious drink today and experience the perfect marriage of coffee and chocolate!",
                            ImageUrl = "https://res.cloudinary.com/durcypdqc/image/upload/v1675704066/Coffee%20Shop%20Asp%20.NET%20Core%20Assets/mocha_a80hlu.png",
                            IsTrendingProduct = false,
                            Name = "Mocha",
                            Price = 22m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Detail = "Macchiato Coffee is a classic espresso-based beverage with a rich, creamy flavor and a smooth, velvety texture. Made from high-quality, hand-selected coffee beans, this drink is the perfect pick-me-up for coffee lovers who want a strong, bold taste without the bitterness or harshness of traditional espresso. With a layer of dense, frothed milk that sits on top of the shot of espresso, the Macchiato Coffee is the perfect balance of bold coffee flavor and creamy sweetness. Whether you're a busy professional in need of a morning boost, or an espresso aficionado seeking a more refined coffee experience, the Macchiato Coffee is the ultimate choice for anyone who loves coffee. So why wait? Visit our online coffee store today and try a Macchiato Coffee today!",
                            ImageUrl = "https://res.cloudinary.com/durcypdqc/image/upload/v1675704064/Coffee%20Shop%20Asp%20.NET%20Core%20Assets/macchiato_jelmpv.png",
                            IsTrendingProduct = true,
                            Name = "Macchiato",
                            Price = 15m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Detail = "Flat White\", Detail = \"Flat White Coffee is a classic espresso-based beverage that is a staple in coffee shops all over the world. This smooth and creamy coffee is made with perfectly pulled shots of espresso, topped with velvety steamed milk and a thin layer of microfoam. This gives the Flat White its signature smooth and creamy texture and a rich, coffee flavor that is balanced by the sweetness of the milk. The Flat White is a perfect coffee for those who love a strong coffee taste with a hint of sweetness. Whether you are a coffee aficionado or just looking for a delicious coffee to start your day, a Flat White from our store is the perfect choice!",
                            ImageUrl = "https://res.cloudinary.com/durcypdqc/image/upload/v1675704064/Coffee%20Shop%20Asp%20.NET%20Core%20Assets/flat-white_icl8cr.png",
                            IsTrendingProduct = false,
                            Name = "Flat White",
                            Price = 18m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Detail = "Decaf Coffee, also known as decaffeinated coffee, is a coffee beverage that has had the majority of its caffeine content removed. It is a perfect option for those who enjoy the taste and aroma of coffee, but want to avoid the stimulating effects of caffeine. Decaf coffee is made from 100% Arabica beans, which are carefully roasted to bring out their natural sweetness and rich flavor. Whether you're a coffee aficionado or just looking for a comforting cup of joe, decaf coffee is the perfect choice. It offers all the delicious taste of regular coffee, without the caffeine jitters, making it an ideal choice for late-night sipping, morning or afternoon pick-me-ups, or simply whenever you want to relax and enjoy a cup of coffee. So why wait? Treat yourself to a delicious cup of decaf coffee today and enjoy the taste of coffee, without the caffeine.",
                            ImageUrl = "https://res.cloudinary.com/durcypdqc/image/upload/v1675704069/Coffee%20Shop%20Asp%20.NET%20Core%20Assets/decaf-coffee_p3bth2.png",
                            IsTrendingProduct = false,
                            Name = "Decaf",
                            Price = 25m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Detail = "Irish coffee is a warm, comforting drink that combines the bold flavor of coffee with the smooth sweetness of Irish whiskey and a touch of cream. Our version of this classic cocktail is made with rich, bold coffee and the finest Irish whiskey for a perfect balance of flavors. The cream is gently whipped to a smooth consistency and poured over the coffee, creating a luxurious, creamy layer that balances the whiskey’s warmth. Whether you’re looking for a cozy drink on a cold day or a fun nightcap after a night out, Irish coffee is a perfect choice. Order yours today and experience the perfect blend of coffee and whiskey.",
                            ImageUrl = "https://res.cloudinary.com/durcypdqc/image/upload/v1675704079/Coffee%20Shop%20Asp%20.NET%20Core%20Assets/Irish_Coffee_ncjb0t.png",
                            IsTrendingProduct = true,
                            Name = "Irish Coffee",
                            Price = 15m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Detail = "Iced coffee is a refreshing and delicious way to enjoy your coffee, perfect for hot summer days or for anyone looking for a cool pick-me-up. Our iced coffee is made with high-quality, freshly brewed coffee, which is then chilled and served over ice. We use only the finest coffee beans, expertly roasted to bring out their rich, full-bodied flavor, ensuring that every sip is a treat. Our iced coffee is available in a variety of flavors, including classic black, vanilla, caramel, and mocha, making it the perfect choice for coffee lovers of all tastes. So why wait? Treat yourself to a cold, refreshing glass of iced coffee today!",
                            ImageUrl = "https://res.cloudinary.com/durcypdqc/image/upload/v1675704079/Coffee%20Shop%20Asp%20.NET%20Core%20Assets/Iced_Coffee_o2nenz.png",
                            IsTrendingProduct = false,
                            Name = "Iced Coffee",
                            Price = 13m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 8,
                            Detail = "Matcha",
                            ImageUrl = "https://www.tastingtable.com/img/gallery/ceremonial-grade-matcha-vs-culinary-grade-matcha-whats-the-difference/l-intro-1658943956.jpg",
                            IsTrendingProduct = false,
                            Name = "Ceremonial Grade",
                            Price = 160m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            Detail = "Matcha",
                            ImageUrl = "https://thumbor.forbes.com/thumbor/fit-in/900x510/https://www.forbes.com/health/wp-content/uploads/2022/03/960x0.jpeg.jpg",
                            IsTrendingProduct = false,
                            Name = "Premium Grade",
                            Price = 160m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            Detail = "Matcha",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/2531/9554/files/culinary-grade-matcha-for-baking.jpg?v=1557956137",
                            IsTrendingProduct = false,
                            Name = "Culinary Grade",
                            Price = 160m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 9,
                            Detail = "Juice",
                            ImageUrl = "https://www.mashed.com/img/gallery/apple-juice-brands-ranked-worst-to-best/l-intro-1621953689.jpg",
                            IsTrendingProduct = false,
                            Name = "Apple Juice",
                            Price = 160m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 9,
                            Detail = "Juice",
                            ImageUrl = "https://bing.com/th?id=OSK.ef8f9ead7c81789047deb52b38e77afc",
                            IsTrendingProduct = false,
                            Name = "Mango Juice",
                            Price = 160m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 9,
                            Detail = "Juice",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0248/9496/3802/files/keep-watermelon-fresh.jpg?v=1675340625",
                            IsTrendingProduct = false,
                            Name = "Watermelon Juice",
                            Price = 160m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 10,
                            Detail = "Smoothie",
                            ImageUrl = "https://www.thespruceeats.com/thmb/JHOfNdO8jq5TEteU3IEiGHusoJE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/blueberry-smoothie-2238438-16_Hero_1-0901a8305220460da963ef7b210629ea.jpg",
                            IsTrendingProduct = false,
                            Name = "Blueberry Smoothie",
                            Price = 160m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 10,
                            Detail = "Smoothie",
                            ImageUrl = "https://brewbuch.com/wp-content/uploads/2023/05/green-tea.jpg",
                            IsTrendingProduct = false,
                            Name = "Spinach Smoothie",
                            Price = 160m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 10,
                            Detail = "Smoothie",
                            ImageUrl = "https://reciperunner.com/wp-content/uploads/2014/01/StrawberrySpinachSmoothie2.jpg",
                            IsTrendingProduct = false,
                            Name = "Peach Smoothie",
                            Price = 160m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 11,
                            Detail = "Salty Snack",
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/images/delish-roastedchickpeas-030-1590498769.jpg?crop=0.763xw:0.572xh;0.0417xw,0.332xh&resize=1200:*",
                            IsTrendingProduct = false,
                            Name = "Roasted Chickpea",
                            Price = 160m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 12,
                            Detail = "Sweet Snack",
                            ImageUrl = "https://i1.wp.com/www.husbandsthatcook.com/wp-content/uploads/2016/02/no-bake-strawberry-cheesecake-parfaits.jpg?fit=2048%2C1365&ssl=1",
                            IsTrendingProduct = false,
                            Name = "Strawberry Cheesecake Parfaits",
                            Price = 160m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 13,
                            Detail = "Salty Snack",
                            ImageUrl = "https://i.ytimg.com/vi/0rwn-434Bhk/maxresdefault.jpg",
                            IsTrendingProduct = false,
                            Name = "Dahi Batata Puri Chaat",
                            Price = 160m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 14,
                            Detail = "Vegan Snack",
                            ImageUrl = "https://th.bing.com/th/id/OSK.49de4b523093a0694d4ac13f9e3f923f?w=184&h=127&rs=2&qlt=80&o=6&cdv=1&dpr=1.5&pid=16.1",
                            IsTrendingProduct = false,
                            Name = "Guacamole and Crackers",
                            Price = 160m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 15,
                            Detail = "Gluten free Snack",
                            ImageUrl = "https://images-prod.healthline.com/hlcmsresource/images/AN_images/gluten-free-snacks-zucchini-pizza.jpg",
                            IsTrendingProduct = false,
                            Name = "Bite-size zucchini pizza",
                            Price = 160m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 16,
                            Detail = "Pies and Cobblers",
                            ImageUrl = "https://th.bing.com/th/id/OSK.HEROqxFe_Y-DUBVz1tqT6in63fo7Z8PBfZWXVV_6cZfhdoU?w=312&h=200&c=7&rs=1&o=6&dpr=1.5&pid=SANGAM",
                            IsTrendingProduct = false,
                            Name = "Apple Pie",
                            Price = 160m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 17,
                            Detail = "Cookie",
                            ImageUrl = "https://www.cookie-coach.co.uk/wp-content/uploads/cookie.jpg",
                            IsTrendingProduct = false,
                            Name = "Chocolate Cookie",
                            Price = 160m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 18,
                            Detail = "Cakes",
                            ImageUrl = "https://png.pngtree.com/thumb_back/fw800/background/20240704/pngtree-a-delicious-black-forest-cake-image_15956356.jpg",
                            IsTrendingProduct = false,
                            Name = "Black Forest Cake",
                            Price = 160m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 19,
                            Detail = "Tarts",
                            ImageUrl = "https://thumbs.dreamstime.com/b/healthy-eating-summer-vegetable-tart-close-up-horizontal-table-73594075.jpg",
                            IsTrendingProduct = false,
                            Name = "Vegetable Tart",
                            Price = 160m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 20,
                            Detail = "   Ice creams",
                            ImageUrl = "https://www.foodrepublic.com/img/gallery/how-to-top-vanilla-ice-cream-with-hot-sauce-the-right-way/l-intro-1684539127.jpg",
                            IsTrendingProduct = false,
                            Name = "Vanilla Ice Cream",
                            Price = 160m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 21,
                            Detail = "Custards",
                            ImageUrl = "https://www.tastingtable.com/img/gallery/17-types-of-custard-desserts-explained/clafoutis-1667413271.webp",
                            IsTrendingProduct = false,
                            Name = "Clafoutis",
                            Price = 160m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 22,
                            Detail = "Brownie",
                            ImageUrl = "https://palm.southbeachdiet.com/wp-content/uploads/2018/06/black-bean-brownies.jpg",
                            IsTrendingProduct = false,
                            Name = "Chocolate Chip Bownie",
                            Price = 160m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 23,
                            Detail = "Pastries",
                            ImageUrl = "https://www.vahrehvah.com/indianfood_org/wp-content/uploads/2010/09/1W25TRR12q.jpg",
                            IsTrendingProduct = false,
                            Name = "Pineapple Pastry",
                            Price = 160m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 24,
                            Detail = "Donut",
                            ImageUrl = "https://www.tastingtable.com/img/gallery/20-popular-types-of-donuts-explained/apple-cider-1695055907.webp",
                            IsTrendingProduct = false,
                            Name = "Apple Cider",
                            Price = 160m
                        });
                });

            modelBuilder.Entity("CoffeeShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Oty")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CoffeeShop.Models.Category", b =>
                {
                    b.HasOne("CoffeeShop.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("CoffeeShop.Models.OrderDetail", b =>
                {
                    b.HasOne("CoffeeShop.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CoffeeShop.Models.Product", b =>
                {
                    b.HasOne("CoffeeShop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoffeeShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("CoffeeShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeShop.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("CoffeeShop.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
